apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bluecompute-customer
  labels:
    app: bluecompute
    micro: customer
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: customer
        tier: backend
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
             "name": "bluecompute-customer-wait-for-couchdb",
             "image": "ellerbrock/alpine-bash-curl-ssl",
             "imagePullPolicy": "IfNotPresent",
             "command": ["/bin/bash", "-c", "until curl --max-time 1 http://{{ .Values.couchdb.service.name }}:{{ .Values.couchdb.service.externalPort }}; do echo waiting for couchdb; /bin/sleep 1; done;"]
          }
        ]'
    spec:
      containers:
      - name: bluecompute-customer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /var/run/secrets/binding-refarch-cloudantdb
          name: binding-refarch-cloudantdb
        - mountPath: /var/run/secrets/hs256-key
          name: hs256-key
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: binding-refarch-cloudantdb
        secret:
          defaultMode: 420
          secretName: {{ .Values.couchdb.binding.name }}
      - name: hs256-key
        secret:
          defaultMode: 420
          secretName: "{{ .Chart.Name }}-{{ .Values.hs256key.secretName }}"
