apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-couchdb
  labels:
{{ toYaml .Values.labels | indent 4 }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ toYaml .Values.labels | indent 8 }}
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      containers:
      - name: bluecompute-customer-couchdb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.binding.name }}
                key: user
          - name: COUCHDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.binding.name }}
                key: password
        volumeMounts:
          - mountPath: /opt/couchdb/data
            name: couchdb-data
            readOnly: false
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 10
          failureThreshold: 10
      volumes:
        - name: couchdb-data
{{ if .Values.existingPVCName }}
          persistentVolumeClaim:
            claimName: {{ .Values.existingPVCName }}
{{ else }}
          hostPath:
            path: /opt/couchdb/data
{{ end }}            
