# Default values for micro-customer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-customer
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: customer-service
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

hs256key:
  skipDelete: true
  secretName: hs256-key
  secret:

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

useBluemix: false

ibmcase-bluemix-service:


ibmcase-couchdb:
  user:
  password:
  service:
    name: customer-couchdb
    type: ClusterIP
    externalPort: 5984
    internalPort: 5984
  binding:
    name: binding-customer-couchdb
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi
  existingPVCName:
  labels:
    app: bluecompute
    micro: customer
    tier: data
  nodename: customerdb
  

