# Default values for micro-customer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-customer
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: customer-service
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

hs256key:
  skipDelete: true
  secretName: hs256-key

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi

couchdb:
  user:
  password:
  service:
    name: customerdb
    type: ClusterIP
    externalPort: 5984
    internalPort: 5984
  binding:
    name: binding-customer-couchdb
  secret:
    name: customer-couchdb-credential
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

