apiVersion: batch/v1
kind: Job
metadata:
  name: {{ (cat .Release.Name "-bind-bluemix-service-" ( .Values.service.name | lower | replace " " "-") "-" ( randAlphaNum 5 | lower )) | nospace | trunc 63 }} 
  namespace: {{ .Release.Namespace }}
  labels:
    bluemixService: {{ .Values.service.name | lower | replace " " "-" }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "34"
spec:
  template:
    metadata:
      name: {{.Release.Name}}-bind-bluemix-service-{{ .Values.service.name | lower | replace " " "-" }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: Never
      containers:
      - name: bind-service
        image: ibmcase/bluemix-cluster-deployer
        command: [ "/bin/bash", "-c" ]
        args: 
        - >
          source /scripts/bx_login.sh; 
          bx cs init; 
          bx cs cluster-service-bind {{ .Values.clusterName }} {{ .Release.Namespace }} "{{ .Values.service.name }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: BX_ORG
          value: {{ .Values.target.org }}
        - name: BX_SPACE
          value: {{ .Values.target.space }}
        - name: BX_API_ENDPOINT
          value: {{ .Values.target.endpoint }}
        - name: BLUEMIX_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.service.name | lower | replace " " "-" }}-bluemix-api-key
              key: api-key
