apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-cleanup-jobs-{{ randAlphaNum 5 | lower }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: bluecompute
    micro: auth
    tier: backend
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade,post-delete
    "helm.sh/hook-weight": "999"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-cleanup-jobs-{{ randAlphaNum 5 | lower }}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cleanup-jobs
        image: ibmcase/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c" ]
        args: 
        - >
            set -x;
            kubectl delete jobs -l chart={{.Chart.Name}}-{{.Chart.Version}},release={{.Release.Name}} --cascade;

