apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.bluemix.service.name | lower | replace " " "-" }}-bluemix-target
  namespace: {{ .Release.Namespace }}
  labels:
    bluemixService: {{ .Values.bluemix.service.name | lower | replace " " "-" }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  bluemix-api-endpoint: {{ .Values.bluemix.target.endpoint }}
  bluemix-org: {{ .Values.bluemix.target.org }}
  bluemix-space: {{ .Values.bluemix.target.space }}
  kube-cluster-name:  {{ .Values.bluemix.clusterName }}
  bluemix-service-name:  {{ .Values.bluemix.service.name }}
  bluemix-service-type:  {{ .Values.bluemix.service.type }}
  bluemix-service-plan:  {{ .Values.bluemix.service.plan }}
