apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name | lower | replace " " "-" }}-bluemix-target
  namespace: {{ .Release.Namespace }}
  labels:
    bluemixService: {{ .Values.service.name | lower | replace " " "-" }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  bluemix-api-endpoint: {{ .Values.target.endpoint | quote }}
  bluemix-org: {{ .Values.target.org | quote }}
  bluemix-space: {{ .Values.target.space | quote }}
  kube-cluster-name:  {{ .Values.clusterName | quote }}
  bluemix-service-name:  {{ .Values.service.name | quote }}
  bluemix-service-type:  {{ .Values.service.type | quote }}
  bluemix-service-plan:  {{ .Values.service.plan | quote }}
