apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name }}-unbind-bluemix-service-{{ .Values.bluemix.service.name | lower | replace " " "-" }}-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    bluemixService: {{ .Values.bluemix.service.name | lower | replace " " "-" }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "34"
spec:
  template:
    metadata:
      name: {{.Release.Name}}-unbind-bluemix-service-{{ .Values.bluemix.service.name | lower | replace " " "-" }}
      labels:
        bluemixService: {{ .Values.bluemix.service.name | lower | replace " " "-" }}
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      restartPolicy: Never
      containers:
      - name: bind-service
        image: ibmcase/bluemix-cluster-deployer
        command: [ "/bin/bash", "-c" ]
        args: 
        - >
          source /scripts/bx_login.sh; 
          bx cs init; 
          bx cs cluster-service-unbind {{ .Values.bluemix.clusterName }} {{ .Release.Namespace }} {{ .Values.bluemix.service.name }}
        imagePullPolicy: IfNotPresent
        env:
        - name: BX_ORG
          value: {{ .Values.bluemix.target.org }}
        - name: BX_SPACE
          value: {{ .Values.bluemix.target.space }}
        - name: BX_API_ENDPOINT
          value: {{ .Values.bluemix.target.endpoint }}
        - name: BLUEMIX_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.bluemix.service.name | lower | replace " " "-" }}-bluemix-api-key
              key: api-key
